Repository scalacenter/bloop, pull requests merged in 2018-04, with the labels that each got.

#408 Update nailgun commit in Dependencies
  project/Dependencies.scala
Labels: docs, install

#416 Remove stale configuration files
  .drone.yml
  build.sbt
  integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/build.sbt
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/changes/build.sbt
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/project/plugins.sbt
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/test
  project/BuildPlugin.scala
  project/build.sbt
  website/content/faq/_index.md
Labels: bug, ergonomics, integrations

#418 Add release notes for v1.0.0-M9
  build.sbt
  notes/v1.0.0-M9.md
Labels: docs

#420 Fix quotes issue in docs and remove one heading level
  website/content/docs/bloop-basics.md
  website/content/docs/configuration-format.md
Labels: bug, docs

#424 Fix/watch waiting for #422
  frontend/src/main/scala/bloop/engine/Interpreter.scala
Labels: community, enhancement, ergonomics

#423 Fix/camel case autocompletion
  frontend/src/main/scala/bloop/cli/completion/Case.scala
  frontend/src/main/scala/bloop/engine/Interpreter.scala
Labels: bug, cli, community

#425 Generalize `sourceDirectories` to `sources`
  backend/src/main/scala/bloop/Compiler.scala
  frontend/src/main/scala/bloop/Project.scala
  frontend/src/main/scala/bloop/engine/Interpreter.scala
  frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
  frontend/src/main/scala/bloop/io/SourceWatcher.scala
  frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
  frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
  frontend/src/test/scala/bloop/tasks/TestUtil.scala
Labels: enhancement, integrations, task / watch

#432 Use Python3 in Homebrew formula
  project/ReleaseUtils.scala
Labels: install

#430 Simple improvement to zsh completion when server is not started
  etc/bash/bloop
  etc/zsh/_bloop
Labels: cli, nailgun

#431 Continue the bsp implementation
  backend/src/main/scala/bloop/Compiler.scala
  backend/src/main/scala/bloop/io/AbsolutePath.scala
  backend/src/main/scala/bloop/logging/Slf4jAdapter.scala
  backend/src/main/scala/bloop/reporter/ClassicFormat.scala
  backend/src/main/scala/bloop/reporter/ConfigurableReporter.scala
  backend/src/main/scala/bloop/reporter/DefaultReporterFormat.scala
  backend/src/main/scala/bloop/reporter/Problem.scala
  backend/src/main/scala/bloop/reporter/Reporter.scala
  backend/src/main/scala/bloop/reporter/ReporterConfig.scala
  backend/src/main/scala/bloop/reporter/ReporterFormat.scala
  backend/src/main/scala/bloop/reporter/ScalacFormat.scala
  frontend/src/main/resources/logback.xml
  frontend/src/main/scala/bloop/Project.scala
  frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
  frontend/src/main/scala/bloop/bsp/BspServer.scala
  frontend/src/main/scala/bloop/bsp/ProjectUris.scala
  frontend/src/main/scala/bloop/cli/ReporterKind.scala
  frontend/src/main/scala/bloop/engine/Dag.scala
  frontend/src/main/scala/bloop/engine/Interpreter.scala
  frontend/src/main/scala/bloop/engine/State.scala
  frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
  frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
  frontend/src/main/scala/bloop/io/SourceWatcher.scala
  frontend/src/main/scala/bloop/logging/BspLogger.scala
  frontend/src/main/scala/bloop/reporter/Problem.scala
  frontend/src/test/scala/bloop/bsp/BspClientTest.scala
  frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
  frontend/src/test/scala/bloop/bsp/ProjectUrisSpec.scala
  frontend/src/test/scala/bloop/engine/DagSpec.scala
  frontend/src/test/scala/bloop/tasks/TestTaskTest.scala
  frontend/src/test/scala/bloop/tasks/TestUtil.scala
  integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
  project/Dependencies.scala
Labels: build server, integrations, priority / high

#434 Improve deficiencies in test infrastructure
  frontend/src/main/scala/bloop/Cli.scala
  frontend/src/main/scala/bloop/cli/Commands.scala
  frontend/src/main/scala/bloop/cli/validation/Validate.scala
  frontend/src/main/scala/bloop/engine/Interpreter.scala
  frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
  frontend/src/main/scala/bloop/testing/TestInternals.scala
  frontend/src/test/scala/bloop/cli/validation/ValidateSuite.scala
  frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala
  frontend/src/test/scala/bloop/testing/TestOptionsSpec.scala
Labels: cli, community build, enhancement, task / test

#436 Use range positions in bsp if Zinc returns them
  backend/src/main/scala/bloop/reporter/DefaultReporterFormat.scala
  backend/src/main/scala/sbt/internal/inc/bloop/ZincInternals.scala
  frontend/src/main/scala/bloop/logging/BspLogger.scala
Labels: build server, integrations, priority / high

#437 Add `ScalaBuildTarget` and project deps to bsp
  frontend/src/main/scala/bloop/Project.scala
  frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
  frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
  frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
  frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
  project/Dependencies.scala
Labels: build server, integrations, priority / high

#438 Improve autocompletion for zsh to be more context-aware for #356
  etc/bash/bloop
  etc/zsh/_bloop
  frontend/src/main/scala/bloop/cli/Commands.scala
  frontend/src/main/scala/bloop/cli/completion/Mode.scala
  frontend/src/main/scala/bloop/engine/Interpreter.scala
Labels: cli, enhancement, ergonomics

#443 Speed up first bloop server load
  frontend/src/main/scala/bloop/Project.scala
  frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
Labels: ergonomics, nailgun, performance

#440 Add systemd service file
  bin/install.py
  etc/systemd/bloop.service
  website/content/docs/installation.md
Labels: ergonomics, install, workflow

#448 Don't return initial cache after aggregating results
  frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
Labels: bug, build server, priority / high

#451 Add freedesktop.org-compliant Desktop Entry
  bin/install.py
  etc/xdg/bloop.desktop
  etc/xdg/bloop.png
  website/content/docs/installation.md
Labels: docs, install, integrations

#452 report column instead of line at column position in bsp
  frontend/src/main/scala/bloop/logging/BspLogger.scala
Labels: bug, community

#445 Add akka and detect 'test->compile' and 'compile->test' better
  build-integrations/sbt-1.0/.sbtopts
  build-integrations/sbt-1.0/build.sbt
  build-integrations/sbt-1.0/project/Integrations.scala
  build-integrations/sbt-1.0/project/build.properties
  integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/bar/src/test/scala/BTest.scala
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/baz/src/main/scala/C.scala
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/build.sbt
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/foo/src/main/scala/A.scala
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/foo/src/test/scala/ATest.scala
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/project/plugins.sbt
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/test
  integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/woo/src/test/scala/D.scala
  project/BuildPlugin.scala
  project/build.properties
Labels: community build, enhancement, integrations

#454 Upgrade metaconfig
  frontend/src/main/scala/bloop/Project.scala
  project/Dependencies.scala
Labels: bug, integrations

#455 Filter out directories that don't exist
  frontend/src/main/scala/bloop/engine/Interpreter.scala
  frontend/src/main/scala/bloop/io/SourceWatcher.scala
  frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
Labels: enhancement, ergonomics
